POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "s3878271@rmit.edu.vn",
    "password":"thisisapassword"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "first_name": "Dung",
    "last_name": "Vuong",
    "email": "s3878271@rmit.edu.vn",
    "password": "thisisapassword",
    "type": "student"
}

###

GET http://localhost:3000/main