POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "v3878281@rmit.edu.vn",
    "password":"thisisapassword"
}

### 
POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "v3878281@rmit.edu.vn",
    "password":"thisisapassword"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "v3878281@rmit.edu.vn",
    "password":"thisisapassword"
}

###

POST http://localhost:4000/account/register
Content-Type: application/json

{
    "first_name": "Tech",
    "last_name": "nician",
    "email": "v3878281@rmit.edu.vn",
    "password": "thisisapassword",
    "type": "admin"
}

###

GET http://localhost:4000/account/getAccount


###

POST http://localhost:4000/account/logout


###
POST http://localhost:4000/component


###
GET http://localhost:4000/component

###
GET http://localhost:4000/component/getMyRequest