POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "v3878281@rmit.edu.vn",
    "password":"thisisapassword"
}

### 
PUT http://localhost:4000/account/setfine
Content-Type: application/json

{
    "fine_message": "LATE_RETURN",
    "fine_description": "someasdfsafd",
    "target_email": "studenttest2@gmail.com" 

}
###
POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "s3891724@rmit.edu.vn",
    "password":"test"
}

###
POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "technician@rmit.edu.vn",
    "password":"test"
}

### 
POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "v3878281@rmit.edu.vn",
    "password":"thisisapassword"
}


###
POST http://localhost:4000/account/login
Content-Type: application/json

{
    "email": "techtest2@gmail.com",
    "password": "test"
}

###

POST http://localhost:4000/account/register
Content-Type: application/json

{
    "first_name": "Tech",
    "last_name": "nician 22222",
    "email": "techtest2@gmail.com",
    "password": "test",
    "type": "technician"
}

###
POST http://localhost:4000/account/register
Content-Type: application/json

{
    "first_name": "stu",
    "last_name": "dent 22222",
    "email": "studenttest2@gmail.com",
    "password": "test",
    "type": "student"
}

###

GET http://localhost:4000/account/getaccount


###

POST http://localhost:4000/account/logout


###
POST http://localhost:4000/component


###
GET http://localhost:4000/component

###
GET http://localhost:4000/request/myRequest

###
GET http://localhost:4000/request/search?email=s3891724@